/* Generates vendor/three.global.js from node_modules/three.

   Why: the game must run by double-clicking index.html, with no internet and no server.
   Chrome refuses ES-module imports over file:// (they're cross-origin, origin "null"),
   which is why the original loaded three from a CDN. Classic scripts have no such rule,
   so we wrap three's ESM build in an IIFE that hands back a THREE global.

   Re-run after bumping three:  node tools/build-three.mjs
*/
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'node_modules/three/build/three.module.min.js');
const OUT = join(ROOT, 'vendor/three.global.js');

const src = readFileSync(SRC, 'utf8');
const ver = JSON.parse(readFileSync(join(ROOT, 'node_modules/three/package.json'), 'utf8')).version;

// The build ends in one `export{a as Foo,b as Bar}` and imports nothing.
if (/import\.meta|(^|[;\n])\s*import[\s{'"]/.test(src))
  throw new Error('three build now imports something — the IIFE wrapper is no longer safe');
const m = src.match(/export\s*\{[^{}]*\}\s*;?\s*$/);
if (!m) throw new Error('could not find the trailing export{...} — three build layout changed');

const names = m[0].replace(/^export\s*\{/, '').replace(/\}\s*;?\s*$/, '')
  .split(',').map(s => s.trim()).filter(Boolean)
  .map(part => {
    const as = part.split(/\s+as\s+/);
    return as.length === 2 ? `${as[1]}:${as[0]}` : part;   // `a as Foo` -> `Foo:a`
  });

const body = src.slice(0, m.index);
const out =
`/* three.js r${ver} — generated by tools/build-three.mjs, do not edit.
   ESM build wrapped as a classic script so file:// works offline. */
var THREE = (function(){
'use strict';
${body}
return {${names.join(',')}};
})();
`;
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out);
console.log(`vendor/three.global.js  <-  three@${ver}  (${(out.length/1024).toFixed(0)}KB, ${names.length} exports)`);
